LearnersGuild/curriculum

- modules/Editor-Basics/README.md
Reword for clarity and conciseness, was a little redundant.
> Reword one 'nice to haves'

- modules/Terminal-Basics/exercises/Customizing-Your-Shell.md
Along with spelling corrections, changed 'that only adds...' to 'you only added...' to keep the subject consistent.
> Fix minor spelling errors

- modules/Foundational-JavaScript-Programming/README.md
Organized 3 glossary links under a new glossary h3 header
> Organize glossary links

- modules/Saving-Progress-With-Git-And-GitHub/README.md
> Reword for clarity

- modules/HTTP-Anatomy/README.md
I was encouraged by the SEP to include this presentation or slides to this module.  I believe this will be beneficial to learners.  Listed below is the link
https://robrich.org/slides/anatomy_of_a_web_request/#/21
> Add anatomy of HTTP presentation to the module

- phases/5/README.md
please merge this bad boy. gracias.
> update phase 5 curriculum page

- modules/Foundational-Programming-in-Node/README.md
Reworded so the word anything didn't appear twice in short succession.
> Reword for clairty

- modules/Relational-Database-Design/README.md
what is ACID ??????? // This would be a good search if you're going to Burning Man or to the 'woods with friends' for the first time. 'What is ACID sql' returned more savory results
> Update 'what is ACID' suggested search term

- modules/Contacts-With-Testing/README.md
Added some .'s and took some out for consistency.
> Fixed puncuation

- modules/3-2-1-Contacts/contacts.js
> Minor changes to 321 Contacts Template

- modules/Node-Input-and-Output/exercises/pipes/README.md
Removed a duplicate word, removed a ` typo, reworded instructions about sending input to STDIN.
> Fix typos, reword for clarity

- modules/Node-Input-and-Output/exercises/Command-Line-Arguments/README.md
Added some ' to for we're in a couple places. Reworded explanation of fill paths showing up in first two arguments.
> Add minor punctuation, reword explanation

- modules/Static-HTTP-Server/exercises/Static-Server/README.md
> Fix minor typo

- modules/Command-Line-Todo-List/README.md
Added two words that were left out.
> Correct minor typo

- modules/Unit-Testing-With-Mocha-And-Chai/README.md
Category Search Terms is empty. Pointing out as it's the only one I've seen like this. I added one as a best guess.
> Search Terms is empty, add one

- modules/Promises/README.md
This one appears to be more authoritative, straightforward, systematic, and mature, better for the methodical learner than the more folksy treatments previously referenced, though it becomes less coherent down the page.
> Added reference

- modules/HTTP-Anatomy/README.md
Capitalized a couple of letters for consistency.
> Fix minor formatting

- modules/HTTP-Anatomy/README.md
Added a suggested link description to match the adjacent links.
> Suggestion to add link description

- modules/Movie-Search-CLI/README.md
Suggested a way to break up the long sentence in Exercise for readability.
> Minor suggestion for readability

- modules/Saving-Progress-With-Git-And-GitHub/README.md
> Fix minor punctuation

- modules/Adding-State-to-HTTP/exercises/Remember-Me-App/README.md
Added some punctuation and capitalized some words for consistency
> Minor formatting correction

- modules/Adding-State-to-HTTP/exercises/Secure-Session-Cookie/README.md
Adds a couple conjunction characters, capitalizes some words for consistency.
> Fix typos and formatting consistency

- cos/README.md
The current title appears to have the narrative voice of the U.S. southern regional vocal dialect. This minor change aims to fix that.
> Over looked typo

- modules/Command-Line-Todo-List-with-SQL/README.md
Some resources that I found useful in understanding how to connect to postgreSQL database from node using the pg module.
> Update README.md with resources

- modules/JavaScript-in-the-Browser/exercises/Mac-Calculator-Clone/README.md
Added a single character b/c it's built-in, not builtin.
> Minor typo correction

- modules/Adding-State-to-HTTP/README.md
Previous formulation implied, grammatically, that state adds itself to your application.
> Grammatical correction

- modules/HTTP-Authentication/README.md
Noticed that session cookie was present, switched it to match the previous correction
and listed terminology. Capitalized a few words for consistency.
> Correct minor typos.

- modules/HTTP-Authentication/README.md
Password encryption is newly introduced in this module. The proposed reading explains best practices. It includes an explanation of the need to make error reports vague, as required by the spec (“incorrect email or password”).
> Added proposed reading.

- modules/RESTful-Routing/README.md
I found this treehouse resource extremely useful in explaining RESTful-routing.
> Adding an exercise resource

- modules/JavaScript-in-the-Browser/exercises/Mac-Calculator-Clone/README.md
There is no link, and I cannot find the alleged repo, so I am guessing it does not exist.
> Deleted unfollowable instruction

- modules/HTTP-Authentication/README.md
> Added missing condition

- modules/3-2-1-Contacts/README.md
- modules/3-2-1-Contacts/solutions/rachel-ftw/contacts.js
Adding a second solution for people to look over.
> adding another solution to 3-2-1 Contact

- modules/Foundational-Programming-in-Node/README.md
The Node JS Youtube Tutorial by net ninja was listed twice.
> Remove duplicate Video link

- modules/CRUD-Mutability--Goal-383/README.md
Added a link to an excellent jQuery tutorial, and an AJAX introduction tutorial.
> Update ReadMe with jQuery/AJAX resources

- modules/Posting-Data-To-The-Server-With-A-Form/README.md
Learners were getting tripped up on the specs so I added this to clarify the instructions.
> Adds clarification to instructions

- SUPPORT.md
Also separated into two more general categories: Individual Support and Phase Group Support
> Add "async code reviews" and "talking tech"

- modules/Postgres-And-Node/README.md
These tutorials walk a Learner through building a VERY simple full stack single page app. I feel this will be useful for Learners who to understand a concept need to see it in action. I found both of these personally very enlightening in my first 6 weeks at the Guild.
> Adds two tutorials to resources

- modules/Terminal-Basics/exercises/Customizing-Your-Shell.md
> Update link to Bash Configurations Demystified

- web-server/assets/src/style/layout.sass
- web-server/assets/src/style/markdown.sass
- web-server/views/navbar.jade
> fixes mobile view for navbar, footer, and markdown-options

- modules/System-Design-Interviews/README.md
- Added link to modules/System-Design-Interviews/README.md
> Add 'system design interview resources' link.

- DEVELOPMENT.md
Add a step that mentions forking the repository, cloning the repository locally, and running the command npm install.
> Add a step for the repo

- modules/JavaScript-in-the-Browser/README.md
If my PR on Mac Calculator Clone is approved, then this change should also be made, to conform to it.
> Reference change to conform to related PR

- digest/index.test.js
> adds test to ensure phase READMEs link to existing modules

- web-server/assets/src/script/skills.js
> filters skill list on window load

- test/WebServerSession.js
- web-server/index.test.js
changed all instances of expectToRecirectToLogin to expectToRedirectToLogin
> minor typo fix
